package app.nocamelstyle.cocktailguide.models

data class Drink(
    val idDrink: String,
"strDrink":"Veteran",
"strDrinkAlternate":null,
"strDrinkES":null,
"strDrinkDE":null,
"strDrinkFR":null,
"strDrinkZH-HANS":null,
"strDrinkZH-HANT":null,
"strTags":null,
"strVideo":null,
"strCategory":"Ordinary Drink",
"strIBA":null,
"strAlcoholic":"Alcoholic",
"strGlass":"Old-fashioned glass",
"strInstructions":"Pour the rum and cherry brandy into an old-fashioned glass almost filled with ice cubes. Stir well.",
"strInstructionsES":null,
"strInstructionsDE":"Den Rum und Kirschlik\u00f6r in ein old-fashioned Glas gie\u00dfen, das fast mit Eisw\u00fcrfeln gef\u00fcllt ist. Gut umr\u00fchren.",
"strInstructionsFR":null,
"strInstructionsZH-HANS":null,
"strInstructionsZH-HANT":null,
"strDrinkThumb":"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/iwml9t1492976255.jpg",
"strIngredient1":"Dark rum",
"strIngredient2":"Cherry brandy",
"strMeasure1":"2 oz ",
"strMeasure2":"1\/2 oz ",
)